"""
Batch 6.7 Phases 3+4 — System Stability Evaluation + State Transition Risk Surface
=============================================================================
Phase 3: System Stability Evaluation for 4 transition scenarios
Phase 4: State Transition Risk Surface with risk scoring, gradients, safest path

Loads from state/transition_simulation.json (generated by Phase 1+2).
If file does not exist, generates synthetic transition trajectory data
based on existing system state and arbitration scenario definitions.

Output: state/state_transition_risk_surface.json
"""

import json
import os
import sys
import math
from copy import deepcopy
from datetime import datetime

# Paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE_DIR = os.path.join(os.path.dirname(BASE_DIR), "state")
TRANSITION_FILE = os.path.join(STATE_DIR, "transition_simulation.json")
OUTPUT_FILE = os.path.join(STATE_DIR, "state_transition_risk_surface.json")
ENVELOPE_FILE = os.path.join(STATE_DIR, "edge_04_execution_envelope.json")
PRIORITY_FILE = os.path.join(STATE_DIR, "execution_priority_report.json")
ARBITRATION_FILE = os.path.join(STATE_DIR, "arbitration_simulation_report.json")
THRESHOLD_FILE = os.path.join(STATE_DIR, "emergent_threshold_model.json")
CONTAMINATION_FILE = os.path.join(STATE_DIR, "contamination_audit.json")

STRUCTURE_LIMITED_MIN = 0.30  # MOF threshold below which state degrades
STRUCTURE_LIMITED_MAX = 0.70  # Above this is FULL


def load_json(path):
    if os.path.exists(path):
        with open(path, "r") as f:
            return json.load(f)
    return None


def load_or_default(path, key_msg):
    data = load_json(path)
    if data:
        print(f"  [OK] Loaded {key_msg}")
    else:
        print(f"  [WARN] {key_msg} not found, using defaults")
    return data


def generate_transition_simulation():
    """Generate synthetic 10-cycle trajectory data for 4 transition scenarios,
    matching the format expected from Phase 1+2 simulation."""
    print("\n--- Generating Synthetic Transition Simulation Data ---")

    # Load existing arbitration scenario data
    arb = load_or_default(ARBITRATION_FILE, "arbitration_simulation_report.json")
    envelope_data = load_or_default(ENVELOPE_FILE, "edge_04_execution_envelope.json")
    priority_data = load_or_default(PRIORITY_FILE, "execution_priority_report.json")

    # System baseline
    baseline = {
        "mof_stability": 0.4609,
        "portfolio_conflict": 0.34,
        "execution_priority": 0.39699,
        "confidence": 0.7656,
        "contamination_resistance": 0.2049,
        "structural_invariance": 0.9543,
        "num_positions": 5,
        "mof_state": "STRUCTURE_LIMITED",
        "inside_envelope": False
    }

    # Threshold model coefficients
    threshold_model = load_or_default(THRESHOLD_FILE, "emergent_threshold_model.json")
    if threshold_model and "threshold_model" in threshold_model:
        tc = threshold_model["threshold_model"]["coefficients"]
        threshold_a = tc["intercept_a"]
        threshold_b = tc["conflict_coefficient_b"]
        threshold_c = tc["stability_coefficient_c"]
    else:
        threshold_a, threshold_b, threshold_c = 0.768967, -0.666667, 3.333333

    # Contamination coefficients
    contamination = load_or_default(CONTAMINATION_FILE, "contamination_audit.json")
    if contamination and "layer_ranking" in contamination:
        rf_cc = next((l["contamination_coefficient"] for l in contamination["layer_ranking"] if l["layer"] == "rf"), 0.5353)
        mof_cc = next((l["contamination_coefficient"] for l in contamination["layer_ranking"] if l["layer"] == "mof"), 0.85)
    else:
        rf_cc = 0.5353
        mof_cc = 0.85

    # Envelope boundaries
    env = envelope_data.get("phase_4_execution_envelope", {}).get("envelope", {}) if envelope_data else {}
    env_conf_min = env.get("conf_min", 0.7)
    env_conf_max = env.get("conf_max", 1.0)
    env_conflict_min = env.get("conflict_min", 0.0)
    env_conflict_max = env.get("conflict_max", 0.3)
    env_mof_min = env.get("mof_min", 0.0)
    env_mof_max = env.get("mof_max", 1.0)

    def is_inside_envelope(conf, conflict, mof):
        return (env_conf_min <= conf <= env_conf_max and
                env_conflict_min <= conflict <= env_conflict_max and
                env_mof_min <= mof <= env_mof_max)

    def compute_rf_variance(conflict, cycles_since_transition, shock=0.0):
        """RF variance model: fn(portfolio_conflict, cycles_since_transition)"""
        base_variance = 0.002 + 0.015 * conflict + 0.001 * math.log(cycles_since_transition + 1) + shock
        return min(base_variance, 0.05)  # cap at 5%

    def compute_execution_priority(conf, invariance, contam_resist, conflict):
        return 0.3 * conf + 0.25 * invariance + 0.15 * contam_resist - 0.3 * conflict

    def compute_dynamic_threshold(mof, conflict):
        return threshold_a + threshold_b * conflict + threshold_c * mof

    def check_lifecycle_orphans(scenario_id, positions_after):
        """Check if any tickets would become orphaned after transition."""
        # Orphans are positions whose signal_id has no matching lifecycle entry
        # For the 4 scenarios, we know the lifecycle outcomes from arbitration data
        orphan_map = {
            "A": False,  # Hold All - no changes
            "B": False,  # Partial close - all tickets still exist
            "C": False,  # Full liquidation + new entry - old ticket gone, new ticket created
            "D": True,   # Hedge augmentation - creates orphan (from arbitration data)
        }
        return orphan_map.get(scenario_id, False)

    def compute_lifecycle_coherence(scenario_id, positions_after):
        """Score 0-1: lifecycle coherence including orphan check and ticket mapping."""
        has_orphans = check_lifecycle_orphans(scenario_id, positions_after)
        if has_orphans:
            return 0.4  # Orphan penalty
        # Check all tickets map correctly (no null tickets except for simulated entries)
        null_tickets = [p for p in positions_after if p.get("ticket") in (None, 0, "SIMULATED") and "OPEN" in str(p.get("_action", ""))]
        if null_tickets:
            return 0.7  # Some simulated entries, minor risk
        return 1.0  # Clean

    # Determine arbitration scenario info
    scenario_defs = []
    if arb and "phase_3_arbitration_simulation" in arb:
        for s in arb["phase_3_arbitration_simulation"]["scenarios"]:
            scenario_defs.append({
                "id": s["scenario"],
                "label": s["label"],
                "predicted_mof_state": s["predicted_mof_state"],
                "positions_after": s["positions_after"],
                "overall_score": s["overall_score"],
            })
    else:
        scenario_defs = [
            {"id": "A", "label": "No Action (Hold All)", "predicted_mof_state": "STRUCTURE_LIMITED",
             "positions_after": [], "overall_score": 0.76},
            {"id": "B", "label": "Partial Adjustment (Reduce Conflicting Exposure)", "predicted_mof_state": "STRUCTURE_LIMITED",
             "positions_after": [], "overall_score": 0.76},
            {"id": "C", "label": "Full Liquidation then Entry", "predicted_mof_state": "INFORMATION_DEGRADED",
             "positions_after": [], "overall_score": 0.67},
            {"id": "D", "label": "Hedge Augmentation", "predicted_mof_state": "STRUCTURE_LIMITED",
             "positions_after": [], "overall_score": 0.48},
        ]

    # Build trajectories for each scenario
    num_cycles = 10
    scenarios_trajectory = {}

    for sd in scenario_defs:
        sid = sd["id"]
        label = sd["label"]
        predicted_mof_state = sd["predicted_mof_state"]
        positions_after = sd.get("positions_after", [])
        overall_score = sd.get("overall_score", 0.5)

        # Determine initial shock / delta based on scenario type
        if sid == "A":
            # Hold All - no change, MOF drifts naturally
            mof_shock = 0.0
            conflict_delta = 0.0
            conf_delta = 0.0
            contam_delta = 0.0
            rf_shock = 0.0
        elif sid == "B":
            # Partial close - reduces conflict slightly, MOF improves
            mof_shock = 0.02
            conflict_delta = -0.10
            conf_delta = 0.01
            contam_delta = 0.02
            rf_shock = 0.001
        elif sid == "C":
            # Full liquidation then entry - MOF degrades significantly
            mof_shock = -0.12
            conflict_delta = 0.08  # New position creates new conflicts
            conf_delta = 0.02
            contam_delta = -0.05
            rf_shock = 0.008
        elif sid == "D":
            # Hedge augmentation - MOF somewhat stable but lifecycle issues
            mof_shock = 0.0
            conflict_delta = 0.05
            conf_delta = 0.01
            contam_delta = -0.02
            rf_shock = 0.004
        else:
            mof_shock = 0.0
            conflict_delta = 0.0
            conf_delta = 0.0
            contam_delta = 0.0
            rf_shock = 0.0

        trajectory = []
        mof = baseline["mof_stability"]
        conflict = baseline["portfolio_conflict"]
        confidence = baseline["confidence"]
        contam_resist = baseline["contamination_resistance"]
        invariance = baseline["structural_invariance"]

        for cycle in range(1, num_cycles + 1):
            # Apply transition impact on cycle 1 (immediate), then dynamics
            if cycle == 1:
                mof += mof_shock
                conflict += conflict_delta
                confidence += conf_delta
                contam_resist += contam_delta
            else:
                # Random walk drift
                import random
                random.seed(hash(f"{sid}_{cycle}") % (2**31))
                mof += random.uniform(-0.015, 0.015)
                conflict += random.uniform(-0.01, 0.01)
                confidence += random.uniform(-0.005, 0.005)
                contam_resist += random.uniform(-0.003, 0.003)
                # Mean reversion on MOF
                mof += 0.02 * (0.45 - mof) * 0.1

            # Clamp
            mof = max(0.1, min(1.0, mof))
            conflict = max(0.0, min(1.0, conflict))
            confidence = max(0.0, min(1.0, confidence))
            contam_resist = max(0.0, min(1.0, contam_resist))

            # Determine MOF state label
            if mof >= STRUCTURE_LIMITED_MAX:
                mof_state_label = "FULL"
            elif mof >= STRUCTURE_LIMITED_MIN:
                mof_state_label = "STRUCTURE_LIMITED"
            else:
                mof_state_label = "INFORMATION_DEGRADED"

            # Compute derived metrics
            priority = compute_execution_priority(confidence, invariance, contam_resist, conflict)
            rf_variance = compute_rf_variance(conflict, cycle, shock=rf_shock)
            dynamic_threshold = compute_dynamic_threshold(mof, conflict)
            in_envelope = is_inside_envelope(confidence, conflict, mof)

            # Decision threshold check
            # Using emergent threshold model: execute if priority >= dynamic_threshold
            # But also check static rule: confidence >= 0.70
            static_execute = confidence >= 0.70
            emergent_execute = priority >= dynamic_threshold

            entry = {
                "cycle": cycle,
                "mof_stability": round(mof, 4),
                "mof_state": mof_state_label,
                "portfolio_conflict": round(conflict, 4),
                "confidence": round(confidence, 4),
                "contamination_resistance": round(contam_resist, 4),
                "execution_priority": round(priority, 4),
                "rf_variance": round(rf_variance, 6),
                "dynamic_threshold": round(dynamic_threshold, 4),
                "inside_envelope": in_envelope,
                "static_execute_decision": static_execute,
                "emergent_execute_decision": emergent_execute,
            }
            trajectory.append(entry)

        # Evaluate lifecycle coherence
        lifecycle_coherence = compute_lifecycle_coherence(sid, positions_after)
        new_orphans = check_lifecycle_orphans(sid, positions_after)

        scenarios_trajectory[sid] = {
            "label": label,
            "overall_score": overall_score,
            "predicted_mof_state": predicted_mof_state,
            "num_positions_after": len(positions_after) if positions_after else baseline["num_positions"],
            "lifecycle_coherence_score": lifecycle_coherence,
            "new_orphans_created": new_orphans,
            "trajectory": trajectory,
        }

    simulation = {
        "report_metadata": {
            "report_type": "TRANSITION_SIMULATION",
            "phase": "Batch 6.7 Phase 1+2 — State Transition Simulation (Synthetic)",
            "edge_id": "edge_04",
            "symbol": "EURJPY",
            "generated_at": datetime.utcnow().isoformat(),
            "num_cycles": num_cycles,
            "source": "synthetic_generation (transition_simulation.json not found)",
        },
        "baseline_state": baseline,
        "envelope": {
            "conf_range": [env_conf_min, env_conf_max],
            "conflict_range": [env_conflict_min, env_conflict_max],
            "mof_range": [env_mof_min, env_mof_max],
        },
        "scenarios": scenarios_trajectory,
    }

    return simulation


def phase3_stability_evaluation(simulation):
    """Phase 3 — System Stability Evaluation across 4 transition scenarios."""
    print("\n" + "=" * 70)
    print("PHASE 3 — SYSTEM STABILITY EVALUATION")
    print("=" * 70)

    scenarios = simulation.get("scenarios", {})
    envelope_info = simulation.get("envelope", {})
    baseline = simulation.get("baseline_state", {})

    stability_results = {}

    for sid, sdata in scenarios.items():
        trajectory = sdata.get("trajectory", [])
        label = sdata.get("label", sid)

        print(f"\n--- Scenario {sid}: {label} ---")

        # 1. MOF Trajectory
        mof_values = [t["mof_stability"] for t in trajectory]
        mof_states = [t["mof_state"] for t in trajectory]
        mof_start = mof_values[0] if mof_values else 0
        mof_end = mof_values[-1] if mof_values else 0
        mof_min = min(mof_values) if mof_values else 0
        mof_drift = mof_end - mof_start

        # Check if MOF stays in STRUCTURE_LIMITED throughout
        sl_states = {"STRUCTURE_LIMITED", "FULL"}
        all_structure_limited = all(s in sl_states for s in mof_states)
        degraded_cycles = [i+1 for i, s in enumerate(mof_states) if s == "INFORMATION_DEGRADED"]

        print(f"  MOF Trajectory:")
        print(f"    Start: {mof_start:.4f}, End: {mof_end:.4f}, Min: {mof_min:.4f}, Drift: {mof_drift:+.4f}")
        print(f"    All cycles in STRUCTURE_LIMITED+: {all_structure_limited}")
        if degraded_cycles:
            print(f"    Degraded cycles: {degraded_cycles}")
        print(f"    Min MOF score observed: {mof_min:.4f}")

        # MOF stability ratio
        initial_mof = baseline.get("mof_stability", mof_start)
        mof_stability_ratio = mof_min / initial_mof if initial_mof > 0 else 0

        # 2. RF Variance Drift
        rf_variances = [t["rf_variance"] for t in trajectory]
        rf_var_start = rf_variances[0] if rf_variances else 0
        rf_var_end = rf_variances[-1] if rf_variances else 0
        rf_var_max = max(rf_variances) if rf_variances else 0
        rf_var_drift = rf_var_end - rf_var_start

        # Bounded if max RF variance < 0.01 threshold
        rf_bounded = rf_var_max < 0.01
        rf_instability = 0 if rf_bounded else 1

        print(f"\n  RF Variance Drift:")
        print(f"    Start: {rf_var_start:.6f}, End: {rf_var_end:.6f}, Max: {rf_var_max:.6f}")
        print(f"    Bounded (<0.01): {rf_bounded}")
        print(f"    Stability classification: {'STABLE' if rf_bounded else 'UNSTABLE'}")

        # 3. Edge_04 Envelope Validity
        inside_counts = sum(1 for t in trajectory if t["inside_envelope"])
        total_cycles = len(trajectory)
        inside_pct = inside_counts / total_cycles * 100 if total_cycles > 0 else 0

        # Check if envelope entry happens when conflict drops below 0.30
        envelope_entry_cycles = [t["cycle"] for t in trajectory if t["inside_envelope"]]
        conflict_at_entry = [t["portfolio_conflict"] for t in trajectory if t["inside_envelope"]]
        envelope_entered_at_low_conflict = any(c < 0.30 for c in conflict_at_entry)

        print(f"\n  Edge_04 Envelope Validity:")
        print(f"    Cycles inside envelope: {inside_counts}/{total_cycles} ({inside_pct:.1f}%)")
        print(f"    Envelope entry at conflict<0.30: {envelope_entered_at_low_conflict}")

        # 4. Lifecycle Coherence
        lifecycle_coherence = sdata.get("lifecycle_coherence_score", 1.0)
        new_orphans = sdata.get("new_orphans_created", False)
        ticket_mapping_ok = lifecycle_coherence >= 0.7

        print(f"\n  Lifecycle Coherence:")
        print(f"    Score: {lifecycle_coherence:.2f}")
        print(f"    New orphans created: {new_orphans}")
        print(f"    Ticket mapping OK: {ticket_mapping_ok}")

        # Compile stability evaluation
        stability_results[sid] = {
            "label": label,
            "mof_trajectory": {
                "start": mof_start,
                "end": mof_end,
                "min": mof_min,
                "drift": mof_drift,
                "all_structure_limited": all_structure_limited,
                "degraded_cycles": degraded_cycles,
                "stability_ratio": mof_stability_ratio,
            },
            "rf_variance_drift": {
                "start": rf_var_start,
                "end": rf_var_end,
                "max": rf_var_max,
                "drift": rf_var_drift,
                "bounded": rf_bounded,
                "instability_flag": rf_instability,
                "classification": "STABLE" if rf_bounded else "UNSTABLE",
            },
            "envelope_validity": {
                "cycles_inside": inside_counts,
                "total_cycles": total_cycles,
                "inside_pct": inside_pct,
                "envelope_entered_at_low_conflict": envelope_entered_at_low_conflict,
                "violation_rate": (total_cycles - inside_counts) / total_cycles if total_cycles > 0 else 1.0,
            },
            "lifecycle_coherence": {
                "score": lifecycle_coherence,
                "new_orphans": new_orphans,
                "ticket_mapping_ok": ticket_mapping_ok,
                "lifecycle_risk": 0.1 if not new_orphans else 0.4,
            },
        }

    return stability_results


def phase4_risk_surface(stability_results, simulation):
    """Phase 4 — State Transition Risk Surface."""
    print("\n" + "=" * 70)
    print("PHASE 4 — STATE TRANSITION RISK SURFACE")
    print("=" * 70)

    scenarios = simulation.get("scenarios", {})
    baseline = simulation.get("baseline_state", {})

    per_scenario_risk = {}
    risk_details = {}

    for sid, sdata in stability_results.items():
        label = sdata["label"]

        # Risk score formula:
        # risk = 0.3*(1 - MOF_stability_ratio) + 0.3*RF_instability + 0.2*lifecycle_risk + 0.2*envelope_violation_rate
        mof_ratio = sdata["mof_trajectory"]["stability_ratio"]
        rf_instability = sdata["rf_variance_drift"]["instability_flag"]
        lifecycle_risk = sdata["lifecycle_coherence"]["lifecycle_risk"]
        envelope_violation = sdata["envelope_validity"]["violation_rate"]

        risk_score = (0.3 * (1 - mof_ratio) +
                      0.3 * rf_instability +
                      0.2 * lifecycle_risk +
                      0.2 * envelope_violation)

        risk_score = round(min(1.0, max(0.0, risk_score)), 4)

        per_scenario_risk[sid] = risk_score
        risk_details[sid] = {
            "label": label,
            "risk_score": risk_score,
            "components": {
                "mof_instability_contribution": round(0.3 * (1 - mof_ratio), 4),
                "rf_instability_contribution": round(0.3 * rf_instability, 4),
                "lifecycle_risk_contribution": round(0.2 * lifecycle_risk, 4),
                "envelope_violation_contribution": round(0.2 * envelope_violation, 4),
            },
            "raw_metrics": {
                "mof_stability_ratio": round(mof_ratio, 4),
                "rf_instability_flag": rf_instability,
                "lifecycle_risk": lifecycle_risk,
                "envelope_violation_rate": round(envelope_violation, 4),
            },
        }

    # Rank by risk score (ascending — lower is safer)
    ranked = sorted(per_scenario_risk.items(), key=lambda x: x[1])
    safest_sid = ranked[0][0] if ranked else None

    print("\n--- Risk Scores per Scenario ---")
    for sid, score in ranked:
        label = risk_details[sid]["label"]
        print(f"  {sid}: {label} — Risk Score: {score:.4f}")

    # 2. Stability Gradient Across Transitions — first derivative from baseline
    # Baseline risk: the risk of doing nothing (Scenario A)
    baseline_sid = "A"
    baseline_risk = per_scenario_risk.get(baseline_sid, 0.5)

    stability_gradients = {}
    for sid, score in per_scenario_risk.items():
        gradient = round(score - baseline_risk, 4)
        stability_gradients[sid] = {
            "label": risk_details[sid]["label"],
            "risk_score": score,
            "baseline_risk": baseline_risk,
            "gradient_from_baseline": gradient,
            "gradient_label": "STEEPER" if gradient > 0 else ("SMOOTHER" if gradient < 0 else "IDENTICAL"),
        }

    steepest = max(stability_gradients.items(), key=lambda x: x[1]["gradient_from_baseline"])
    smoothest = min(stability_gradients.items(), key=lambda x: x[1]["gradient_from_baseline"])

    print(f"\n--- Stability Gradients (risk delta from baseline '{baseline_sid}': {baseline_risk:.4f}) ---")
    for sid, g in sorted(stability_gradients.items()):
        print(f"  {sid}: delta={g['gradient_from_baseline']:+.4f} ({g['gradient_label']})")
    print(f"  Steepest transition: {steepest[0]} (delta={steepest[1]['gradient_from_baseline']:+.4f})")
    print(f"  Smoothest transition: {smoothest[0]} (delta={smoothest[1]['gradient_from_baseline']:+.4f})")

    # 3. Safest Executable Path
    safest_path = ranked[0] if ranked else ("N/A", 1.0)
    recommended_path = risk_details[safest_sid]["label"] if safest_sid else "N/A"

    print(f"\n--- Safest Executable Path ---")
    print(f"  Ranked by risk score (lower = safer):")
    for i, (sid, score) in enumerate(ranked, 1):
        label = risk_details[sid]["label"]
        print(f"    {i}. {sid}: {label} (risk={score:.4f})")
    print(f"  Recommended: {recommended_path}")

    # 4. Edge_04 Envelope Behavior Under State Mutation
    envelope_analysis = {}
    for sid, sdata in stability_results.items():
        label = sdata["label"]
        ev = sdata["envelope_validity"]
        before_envelope = simulation.get("baseline_state", {}).get("inside_envelope", False)
        after_inside_pct = ev["inside_pct"]

        # Envelope shrinks or expands?
        if after_inside_pct > 50:
            envelope_verdict = "EXPANDED — higher viability after transition"
            viability_change = "MORE_VIABLE"
        elif after_inside_pct > 10:
            envelope_verdict = "STABLE — marginal change in envelope viability"
            viability_change = "STABLE"
        else:
            envelope_verdict = "SHRUNK — reduced envelope viability after transition"
            viability_change = "LESS_VIABLE"

        envelope_analysis[sid] = {
            "label": label,
            "before_transition_inside_envelope": before_envelope,
            "after_transition_inside_pct": after_inside_pct,
            "envelope_behavior": envelope_verdict,
            "edge_04_viability": viability_change,
        }

    print(f"\n--- Edge_04 Envelope Behavior Under State Mutation ---")
    for sid, ea in envelope_analysis.items():
        print(f"  {sid} ({ea['label']}):")
        print(f"    Before: inside={ea['before_transition_inside_envelope']}")
        print(f"    After: {ea['after_transition_inside_pct']:.1f}% inside envelope")
        print(f"    Verdict: {ea['envelope_behavior']}")

    # Build output
    output = {
        "report_metadata": {
            "report_type": "STATE_TRANSITION_RISK_SURFACE",
            "phase": "Batch 6.7 Phases 3+4 — System Stability Evaluation + State Transition Risk Surface",
            "edge_id": "edge_04",
            "symbol": "EURJPY",
            "generated_at": datetime.utcnow().isoformat(),
            "source_transition_data": simulation.get("report_metadata", {}).get("source", "synthetic"),
            "constraints": [
                "NO_REAL_MT5_EXECUTION",
                "NO_NEW_TRADES",
                "PURE_SIMULATION",
            ],
        },
        "phase_3_stability_evaluation": stability_results,
        "phase_4_risk_surface": {
            "per_scenario_risk_score": risk_details,
            "risk_ranking": [
                {
                    "rank": i + 1,
                    "scenario": sid,
                    "label": risk_details[sid]["label"],
                    "risk_score": per_scenario_risk[sid],
                }
                for i, (sid, _) in enumerate(ranked)
            ],
            "stability_gradients": stability_gradients,
            "steepest_transition": {
                "scenario": steepest[0],
                "gradient": steepest[1]["gradient_from_baseline"],
                "label": steepest[1]["label"],
            },
            "smoothest_transition": {
                "scenario": smoothest[0],
                "gradient": smoothest[1]["gradient_from_baseline"],
                "label": smoothest[1]["label"],
            },
            "safest_executable_path": {
                "recommended_scenario": safest_sid,
                "recommended_label": recommended_path,
                "risk_score": safest_path[1],
                "ranking": [
                    {
                        "rank": i + 1,
                        "scenario": sid,
                        "label": risk_details[sid]["label"],
                        "risk_score": per_scenario_risk[sid],
                    }
                    for i, (sid, _) in enumerate(ranked)
                ],
            },
            "edge_04_envelope_behavior": envelope_analysis,
        },
        "verdict": {
            "safest_path": recommended_path,
            "safest_risk_score": safest_path[1],
            "recommendation_rationale": (
                f"Scenario {safest_sid} ({recommended_path}) has the lowest composite risk score "
                f"of {safest_path[1]:.4f}, combining MOF stability, RF variance boundedness, "
                f"lifecycle coherence, and envelope compliance."
            ),
            "edge_04_readiness": "DEFER" if safest_path[1] > 0.3 else "OBSERVE",
        },
    }

    return output


def main():
    print("=" * 70)
    print("BATCH 6.7 — SYSTEM STABILITY EVALUATION + STATE TRANSITION RISK SURFACE")
    print("=" * 70)

    # Step 1: Load or generate transition simulation data
    if os.path.exists(TRANSITION_FILE):
        print(f"\nLoading transition simulation from: {TRANSITION_FILE}")
        with open(TRANSITION_FILE, "r") as f:
            simulation = json.load(f)
        print("  [OK] Loaded successfully")
    else:
        print(f"\nTransition simulation not found at: {TRANSITION_FILE}")
        print("Generating synthetic simulation data from existing state files...")
        simulation = generate_transition_simulation()
        print("  [OK] Synthetic simulation generated")

    # Step 2: Phase 3 — Stability Evaluation
    stability_results = phase3_stability_evaluation(simulation)

    # Step 3: Phase 4 — Risk Surface
    risk_surface = phase4_risk_surface(stability_results, simulation)

    # Step 4: Save output
    os.makedirs(STATE_DIR, exist_ok=True)
    with open(OUTPUT_FILE, "w") as f:
        json.dump(risk_surface, f, indent=2, default=str)
    print(f"\n  [OK] Risk surface saved to: {OUTPUT_FILE}")

    # Step 5: Summary
    print("\n" + "=" * 70)
    print("SUMMARY — STATE TRANSITION RISK SURFACE REPORT")
    print("=" * 70)

    ranking = risk_surface["phase_4_risk_surface"]["risk_ranking"]
    print("\nRisk Score per Scenario (0-1, lower = safer):")
    for r in ranking:
        print(f"  Rank {r['rank']}: {r['scenario']} — {r['label']} — Risk: {r['risk_score']:.4f}")

    safest = risk_surface["phase_4_risk_surface"]["safest_executable_path"]
    print(f"\nSafest Path Recommendation: {safest['recommended_label']}")
    print(f"  Risk Score: {safest['risk_score']:.4f}")

    print(f"\nEdge_04 Envelope Behavior:")
    env_behav = risk_surface["phase_4_risk_surface"]["edge_04_envelope_behavior"]
    for sid, ea in env_behav.items():
        print(f"  {sid}: {ea['envelope_behavior']}")

    print(f"\nVerdict: {risk_surface['verdict']['recommendation_rationale']}")
    print(f"  Edge_04 Readiness: {risk_surface['verdict']['edge_04_readiness']}")

    return risk_surface


if __name__ == "__main__":
    result = main()
