"""
PHASE 10 — FINAL ADJUDICATION

Synthesize all findings from Phases 1-9 into RISK_REALITY_REPORT.md.
"""

import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))


def main():
    output_dir = os.path.join(os.path.dirname(__file__), "reports")
    os.makedirs(output_dir, exist_ok=True)

    lines = []
    lines.append("# Risk Reality Report — Final Adjudication")
    lines.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append("The deployment risk engine contains **two mathematically incorrect formulas**")
    lines.append("that together prevent multi-asset trading. The system is effectively captive")
    lines.append("to EURUSD because the risk verifier happens to produce acceptable values")
    lines.append("for EURUSD (by coincidence), while rejecting all other assets.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q1: Is the risk model mathematically correct?")
    lines.append("")
    lines.append("**NO.** Both `calculate_volume()` and the `TradeRiskVerifier` are incorrect.")
    lines.append("")
    lines.append("### Bug 1: `OrderManager.calculate_volume()`")
    lines.append("")
    lines.append("```python")
    lines.append("if 'JPY' in symbol:")
    lines.append("    point_value_per_lot = 100.0 / price  # WRONG: should be 1000.0 / price")
    lines.append("else:")
    lines.append("    point_value_per_lot = 1.0  # WRONG: should be $10/pip for FX, $10/pip for XAU")
    lines.append("```")
    lines.append("")
    lines.append("**Impact**: Calculated lot sizes are ~10x too large for all assets.")
    lines.append("- EURUSD: 1.0 lots instead of 0.12 lots")
    lines.append("- USDJPY: 1.0 lots instead of 0.20 lots")
    lines.append("- XAUUSD: 0.62 lots instead of 0.01 lots")
    lines.append("")
    lines.append("### Bug 2: `TradeRiskVerifier.verify()`")
    lines.append("")
    lines.append("```python")
    lines.append("point_value_per_lot = 1.0  # WRONG: hardcoded for ALL symbols")
    lines.append("```")
    lines.append("")
    lines.append("**Impact**: Dollar risk is calculated incorrectly for every asset class.")
    lines.append("- EURUSD: Reports $50 risk when actual risk = $500 (10x under)")
    lines.append("- USDJPY: Reports $500 risk when actual risk = $312 (60% over)")
    lines.append("- XAUUSD: Reports $500 risk when actual risk = $5,000 (10x under)")
    lines.append("")
    lines.append("### Bug 3: Inconsistent pip-to-point conversion")
    lines.append("")
    lines.append("`calculate_volume()` treats `assumed_sl_points` as pips (50 pips),")
    lines.append("while `TradeRiskVerifier` converts pips to points differently per asset:")
    lines.append("- FX: 1 pip = 10 points → stop_points = 50 × 10 = 500")
    lines.append("- JPY: 1 pip = 10 points → stop_points = 50 × 10 = 500 (but pip value wrong)")
    lines.append("- XAU: 1 pip = 1 point → stop_points = 500 × 1 = 500")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q2: Is the broker preventing research expression?")
    lines.append("")
    lines.append("**NO.** Broker constraints (Phase 8) are correctly configured:")
    lines.append("- Contract sizes: 100,000 FX / 100 gold — MATCH")
    lines.append("- Volume steps: 0.01 for all — MATCH")
    lines.append("- Trade mode: ENABLED — MATCH")
    lines.append("- Stops level: Verified per symbol")
    lines.append("")
    lines.append("The broker would accept correctly-sized orders for all assets.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q3: Are stop assumptions unrealistic?")
    lines.append("")
    lines.append("**Mostly reasonable.** Phase 4 analysis of 30 days of H1 data:")
    lines.append("")
    lines.append("| Asset | Config Stop | 95th %ile Adverse | Classification |")
    lines.append("|-------|-------------|-------------------|----------------|")
    lines.append("| EURJPY | 50 pips | 24.4 pips | REASONABLE |")
    lines.append("| USDJPY | 50 pips | 22.6 pips | REASONABLE |")
    lines.append("| GBPJPY | 70 pips | 31.9 pips | REASONABLE |")
    lines.append("| XAUUSD | 500 pips | 3,175 pips | TOO_TIGHT |")
    lines.append("| EURUSD | 50 pips | 15.6 pips | REASONABLE |")
    lines.append("| NAS100 | 1,000 pips | 18,150 pips | TOO_TIGHT |")
    lines.append("")
    lines.append("XAUUSD and NAS100 catastrophic stops need widening to survive normal")
    lines.append("market moves. However, these stops exist only for VPS/broker crash")
    lines.append("survival, NOT as the research stop-loss. The research holding period")
    lines.append("stop is managed separately by H20 exit logic.")
    lines.append("")
    lines.append("**Finding**: Not the primary bottleneck, but XAU/NAS100 stops are tight.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q4: Is 0.25% risk physically viable?")
    lines.append("")
    lines.append("**YES, with correct formulas.**")
    lines.append("")
    lines.append("| Asset | Correct Volume at 0.25% | Dollar Risk | Achievable? |")
    lines.append("|-------|------------------------|-------------|-------------|")
    lines.append("| EURJPY | 0.23 lots | $62.16 | YES (step=0.01) |")
    lines.append("| USDJPY | 0.20 lots | $62.50 | YES |")
    lines.append("| GBPJPY | 0.19 lots | $62.16 | YES |")
    lines.append("| XAUUSD | 0.01 lots | $50.00 | YES (at min lot) |")
    lines.append("| EURUSD | 0.12 lots | $60.00 | YES |")
    lines.append("| NAS100 | 0.01 lots | $100.00 | MARGINAL (0.01 lot × $1000 = $100) |")
    lines.append("")
    lines.append("NAS100 minimum achievable risk at 0.01 lot = $100, which exceeds $62.50 budget.")
    lines.append("NAS100 requires either higher budget or narrower stop to be tradeable at 0.25%.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q5: Which assets are tradeable?")
    lines.append("")
    lines.append("| Asset | CURRENT (broken) | CORRECTED |")
    lines.append("|-------|-----------------|-----------|")
    lines.append("| EURJPY | NO (risk verifier rejects) | YES |")
    lines.append("| USDJPY | NO (risk verifier rejects) | YES |")
    lines.append("| GBPJPY | NO (risk verifier rejects) | YES |")
    lines.append("| XAUUSD | NO (risk verifier rejects) | YES |")
    lines.append("| EURUSD | YES (by accident) | YES |")
    lines.append("| NAS100 | NO (risk verifier rejects) | MARGINAL |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q6: Which assets are impossible under current rules?")
    lines.append("")
    lines.append("All non-EURUSD assets are impossible under current rules due to the")
    lines.append("broken position sizing and risk verification formulas.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q7: Is the deployment currently under-sized?")
    lines.append("")
    lines.append("**No — it's mis-sized.** EURUSD is over-sized (10x too large) while every")
    lines.append("other asset is effectively zero-sized (because the verifier rejects them).")
    lines.append("The total deployed risk is $500/trade on EURUSD (should be $60).")
    lines.append("The system risks 2% of capital per EURUSD trade, not the intended 0.25%.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q8: What exact changes are justified by evidence?")
    lines.append("")
    lines.append("TWO changes are justified, both in `OrderManager.calculate_volume()`:")
    lines.append("")
    lines.append("### Change 1: Fix pip value for JPY pairs")
    lines.append("```python")
    lines.append("# BEFORE:")
    lines.append("point_value_per_lot = 100.0 / price")
    lines.append("# AFTER:")
    lines.append("point_value_per_lot = 1000.0 / price  # 100,000 * 0.01 / rate")
    lines.append("```")
    lines.append("")
    lines.append("### Change 2: Fix pip value for non-JPY pairs")
    lines.append("```python")
    lines.append("# BEFORE:")
    lines.append("point_value_per_lot = 1.0")
    lines.append("# AFTER (either):")
    lines.append("point_value_per_lot = 10.0  # $10/pip for standard FX")
    lines.append("# OR use risk_amount directly:")
    lines.append("lots = risk_amount / (SL_pips * pip_value_per_lot)")
    lines.append("```")
    lines.append("")
    lines.append("NO changes to: risk percentage, stop distances, position limits, governors.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q9: What changes are NOT justified?")
    lines.append("")
    lines.append("- Increasing risk_per_trade above 0.25% (not needed)")
    lines.append("- Widening catastrophic stops (not the bottleneck)")
    lines.append("- Changing exposure limits (limits are fine)")
    lines.append("- Modifying the governor (governors are healthy)")
    lines.append("- Changing broker (broker constraints match)")
    lines.append("- Adding new assets to research (research is frozen)")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Q10: What is the true bottleneck?")
    lines.append("")
    lines.append("**Position sizing formula in `OrderManager.calculate_volume()`**")
    lines.append("")
    lines.append("The single function at:")
    lines.append("```")
    lines.append("proxima_ops/execution/order_manager.py:10  (calculate_volume)")
    lines.append("```")
    lines.append("")
    lines.append("is responsible for every rejection. Fixing this one function to use")
    lines.append("correct pip values would make all 6 assets tradeable at 0.25% risk.")
    lines.append("")
    lines.append("The `TradeRiskVerifier.verify()` also has a hardcoded `point_value_per_lot = 1.0`")
    lines.append("that produces incorrect dollar risk values, but since the verifier and the")
    lines.append("sizing formula use the same wrong units, fixing only `calculate_volume()`")
    lines.append("would make volumes small enough that even the broken verifier would accept them.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Final Classification")
    lines.append("")
    lines.append("```text")
    lines.append("CURRENT STATE:  RISK_ENGINE_BROKEN")
    lines.append("AFTER FIX:      RISK_ENGINE_HEALTHY")
    lines.append("```")
    lines.append("")
    lines.append("**Not** broker-constrained.")
    lines.append("**Not** governor-constrained.")
    lines.append("**Not** stop-constrained.")
    lines.append("")
    lines.append("**Sizing-formula-constrained.** Two lines of code.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Appendices")
    lines.append("")
    lines.append("| Phase | Report | Finding |")
    lines.append("|-------|--------|---------|")
    lines.append("| 1 | `risk_trace.jsonl` | ALL 25 scenarios rejected (100%) |")
    lines.append("| 2 | `ASSET_RISK_AUDIT.md` | All assets TRADEABLE at correct sizing |")
    lines.append("| 3 | `POSITION_SIZING_AUDIT.md` | 30/30 volume MISMATCH, verifier 30/30 WRONG |")
    lines.append("| 4 | `STOP_DISTANCE_AUDIT.md` | FX stops REASONABLE, XAU/NAS TOO_TIGHT |")
    lines.append("| 5/6 | `EXPRESSION_CAPACITY.md` | NOT_EXPRESSIBLE -> RESEARCH_EXPRESSIBLE |")
    lines.append("| 7 | `RISK_GOVERNOR_IMPACT.md` | GOVENORS_HEALTHY |")
    lines.append("| 8 | `BROKER_CONSTRAINTS.md` | BROKER_REALITY_MATCHES |")
    lines.append("| 9 | `DEPLOYMENT_FRICTION_REPORT.md` | 100% friction at risk engine |")
    lines.append("")
    lines.append("*End of Report*")

    report_path = os.path.join(output_dir, "RISK_REALITY_REPORT.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Report: {report_path}")


if __name__ == "__main__":
    main()
