from typing import Dict, Tuple

CURRENCY_LIST = ["EUR", "USD", "GBP", "JPY", "CHF", "AUD", "CAD", "NZD"]

BASE_CURRENCY_MAP: Dict[str, Tuple[str, str]] = {
    "EURUSD": ("EUR", "USD"),
    "EURGBP": ("EUR", "GBP"),
    "EURJPY": ("EUR", "JPY"),
    "EURCHF": ("EUR", "CHF"),
    "EURAUD": ("EUR", "AUD"),
    "EURCAD": ("EUR", "CAD"),
    "EURNZD": ("EUR", "NZD"),
    "GBPUSD": ("GBP", "USD"),
    "GBPJPY": ("GBP", "JPY"),
    "GBPCHF": ("GBP", "CHF"),
    "GBPAUD": ("GBP", "AUD"),
    "GBPCAD": ("GBP", "CAD"),
    "GBPNZD": ("GBP", "NZD"),
    "USDJPY": ("USD", "JPY"),
    "USDCHF": ("USD", "CHF"),
    "USDAUD": ("USD", "AUD"),
    "USDCAD": ("USD", "CAD"),
    "USDNZD": ("USD", "NZD"),
    "JPYCHF": ("JPY", "CHF"),
    "JPYAUD": ("JPY", "AUD"),
    "JPYCAD": ("JPY", "CAD"),
    "JPYNZD": ("JPY", "NZD"),
    "CHFAUD": ("CHF", "AUD"),
    "CHFCAD": ("CHF", "CAD"),
    "CHFNZD": ("CHF", "NZD"),
    "AUDCAD": ("AUD", "CAD"),
    "AUDNZD": ("AUD", "NZD"),
    "CADNZD": ("CAD", "NZD"),
}

WLS_REGULARIZATION: float = 0.01
MIN_SOLVE_PAIRS = 10

SYMBOLS = list(BASE_CURRENCY_MAP.keys())

MAX_POSITIONS = 3
MAX_EXPOSURE_PER_CURRENCY = 200_000
STOP_LOSS_PIPS = 30
TAKE_PROFIT_PIPS = 60
MAX_HOLD_HOURS = 12
MIN_CONFIDENCE = 0.06
MIN_SPREAD = 0.00002
SIGNAL_EXPIRY_SECONDS = 300

WLS_SMOOTH_ALPHA = 0.2
BURST_TOP_N = 5

MAX_TICK_AGE_SECONDS = 120
MIN_SYMBOL_COVERAGE = 0.70
MAX_SPREAD_MULTIPLE = 5

INITIAL_CAPITAL = 10_000
LOT_SIZE = 1.0
MAX_TOTAL_LOTS = 3.0
PROFIT_TARGET = 50.0
STOP_LOSS_AMOUNT = -60.0
PROFIT_COOLDOWN = 300
CHOP_CLOSE_DELAY_SECONDS = 0
MIN_TRADE_RUNTIME_SECONDS = 30

EXECUTION_MODE = "live"  # "paper" for simulated, "live" for real MT5 order placement
WLS_DIRECT_MODE = True  # bypass legacy gate layers
MAX_DAILY_LOSS = 100
MAX_DRAWDOWN = 500
MAX_CURRENCY_POSITIONS = 2
MIN_TP_SL_PIPS = 4
DRS_LAMBDA_DECAY = 0.05
DRS_REPLACE_MARGIN = 0.10
DRS_SLOT_INERTIA = [1.0, 0.85, 0.7]
MAX_CURRENCY_FACTOR_EXPOSURE = 2
DRS_CANDIDATE_POOL_SIZE = 10
MIN_GRAPH_CONNECTIVITY = 0.45
DIRECTION_PERSISTENCE_CYCLES = 3


